apiVersion: v1
kind: ServiceAccount
metadata:
  name: review-backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: review-frontend
automountServiceAccountToken: false
