{{- if not .Values.persistence.history.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/part-of: local-review-demo
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  name: review-history
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.history.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
